export const ROLES_CONFIG: Record<string, any> = {
  admin: {
    name: "Administrator",
    department: "Management",
    position: "System Administrator",
    permissions: [
      "manage_all",
      "manage_employees",
      "manage_finance",
      "manage_compliance",
      "manage_settings",
      "view_analytics",
      "export_data",
    ],
    accessibleModules: [
      "dashboard",
      "employees",
      "finance",
      "leave",
      "assets",
      "requests",
      "projects",
      "analytics",
      "payroll",
      "training",
      "recruitment",
      "communication",
      "compliance",
      "search",
      "bulkActions",
      "notifications",
      "settings",
    ],
  },
  hr_manager: {
    name: "HR Manager",
    department: "Human Resources",
    position: "HR Manager",
    permissions: [
      "manage_employees",
      "manage_training",
      "manage_recruitment",
      "view_leave_requests",
      "approve_leave",
      "view_analytics",
      "export_data",
    ],
    accessibleModules: [
      "dashboard",
      "employees",
      "leave",
      "requests",
      "training",
      "recruitment",
      "communication",
      "analytics",
      "notifications",
      "search",
    ],
  },
  finance_manager: {
    name: "Finance Manager",
    department: "Finance",
    position: "Finance Manager",
    permissions: [
      "manage_finance",
      "manage_expenses",
      "approve_expenses",
      "manage_payroll",
      "view_analytics",
      "export_data",
    ],
    accessibleModules: [
      "dashboard",
      "finance",
      "payroll",
      "assets",
      "requests",
      "analytics",
      "notifications",
      "search",
    ],
  },
  department_manager: {
    name: "Department Manager",
    department: "Various",
    position: "Department Manager",
    permissions: [
      "view_team_employees",
      "manage_team_requests",
      "approve_team_leave",
      "manage_team_projects",
      "view_team_analytics",
    ],
    accessibleModules: [
      "dashboard",
      "employees",
      "leave",
      "requests",
      "projects",
      "analytics",
      "communication",
      "notifications",
      "search",
    ],
  },
  employee: {
    name: "Employee",
    department: "Various",
    position: "Employee",
    permissions: ["view_own_profile", "request_leave", "view_payslip", "submit_request", "view_projects"],
    accessibleModules: ["dashboard", "leave", "requests", "projects", "communication", "notifications", "search"],
  },
  finance_officer: {
    name: "Finance Officer",
    department: "Finance",
    position: "Finance Officer",
    permissions: ["manage_expenses", "view_finance_reports", "export_finance_data"],
    accessibleModules: ["dashboard", "finance", "requests", "notifications", "search"],
  },
  recruiter: {
    name: "Recruiter",
    department: "Human Resources",
    position: "Recruiter",
    permissions: ["manage_recruitment", "manage_job_postings", "view_candidates"],
    accessibleModules: ["dashboard", "recruitment", "employees", "communication", "notifications", "search"],
  },
  training_coordinator: {
    name: "Training Coordinator",
    department: "Human Resources",
    position: "Training Coordinator",
    permissions: ["manage_training", "track_certifications", "schedule_training"],
    accessibleModules: ["dashboard", "training", "employees", "communication", "notifications", "search"],
  },
}
