export const getRoleDefaultModule = (role: string): string => {
  // All roles now use unified "dashboard" - it will show role-specific content
  return "dashboard"
}

export const isModuleAccessible = (role: string, module: string): boolean => {
  const roleModuleAccess: Record<string, string[]> = {
    super_admin: [
      "dashboard",
      "employees",
      "finance",
      "leave",
      "assets",
      "requests",
      "projects",
      "analytics",
      "payroll",
      "training",
      "recruitment",
      "communication",
      "compliance",
      "search",
      "bulkActions",
      "notifications",
      "settings",
    ],
    executive: ["dashboard", "analytics", "finance", "employees", "notifications", "search"],
    hr_head: [
      "dashboard",
      "employees",
      "leave",
      "requests",
      "training",
      "recruitment",
      "communication",
      "analytics",
      "notifications",
      "search",
    ],
    hr_officer: ["dashboard", "employees", "leave", "requests", "communication", "notifications", "search"],
    finance_director: [
      "dashboard",
      "finance",
      "payroll",
      "assets",
      "requests",
      "analytics",
      "bulkActions",
      "notifications",
      "search",
    ],
    accountant: ["dashboard", "finance", "requests", "notifications", "search"],
    finance_officer: ["dashboard", "finance", "requests", "notifications", "search"],
    dept_manager: [
      "dashboard",
      "employees",
      "leave",
      "requests",
      "projects",
      "analytics",
      "communication",
      "notifications",
      "search",
    ],
    employee: ["dashboard", "leave", "requests", "projects", "communication", "notifications", "search"],
    it_manager: ["dashboard", "employees", "requests", "analytics", "compliance", "notifications", "search"],
    it_support: ["dashboard", "requests", "notifications", "search"],
    recruiter: ["dashboard", "recruitment", "employees", "communication", "notifications", "search"],
    trainer: ["dashboard", "training", "employees", "communication", "notifications", "search"],
    compliance_officer: ["dashboard", "compliance", "analytics", "notifications", "search"],
    procurement_officer: ["dashboard", "assets", "finance", "requests", "notifications", "search"],
    facilities_manager: ["dashboard", "assets", "requests", "communication", "notifications", "search"],
    project_manager: ["dashboard", "projects", "employees", "requests", "analytics", "communication", "notifications", "search"],
    support_manager: ["dashboard", "requests", "communication", "analytics", "notifications", "search"],
    wellness_manager: ["dashboard", "communication", "employees", "analytics", "notifications", "search"],
    hse_manager: ["dashboard", "compliance", "analytics", "requests", "communication", "notifications", "search"],
    csr_manager: ["dashboard", "projects", "analytics", "communication", "notifications", "search"],
    rnd_manager: ["dashboard", "projects", "assets", "analytics", "communication", "notifications", "search"],
    security_manager: ["dashboard", "compliance", "analytics", "settings", "notifications", "search"],
    security_admin: ["dashboard", "compliance", "analytics", "settings", "notifications", "search"],
    audit_head: [
      "dashboard",
      "compliance",
      "analytics",
      "employees",
      "finance",
      "requests",
      "assets",
      "notifications",
      "search",
      "audit-logs",
      "audit-reports",
      "risk-assessment",
    ],
    audit_manager: [
      "dashboard",
      "compliance",
      "audit-logs",
      "audit-reports",
      "risk-assessment",
      "analytics",
      "notifications",
      "search",
    ],
    internal_auditor: ["dashboard", "audit-logs", "audit-reports", "risk-assessment", "notifications", "search"],
  }
  return roleModuleAccess[role]?.includes(module) || false
}

export const getRoleDisplayName = (role: string): string => {
  const roleNames: Record<string, string> = {
    super_admin: "Super Administrator",
    executive: "Executive",
    hr_head: "HR Head",
    hr_officer: "HR Officer",
    finance_director: "Finance Director",
    accountant: "Accountant",
    finance_officer: "Finance Officer",
    dept_manager: "Department Manager",
    employee: "Employee",
    it_manager: "IT Manager",
    it_support: "IT Support",
    recruiter: "Recruiter",
    trainer: "Trainer",
    compliance_officer: "Compliance Officer",
    procurement_officer: "Procurement Officer",
    facilities_manager: "Facilities Manager",
    project_manager: "Project Manager",
    support_manager: "Support Manager",
    wellness_manager: "Wellness Manager",
    hse_manager: "HSE Manager",
    csr_manager: "CSR Manager",
    audit_head: "Audit Head",
    audit_manager: "Audit Manager",
    internal_auditor: "Internal Auditor",
  }
  return roleNames[role] || role
}
